### ISSUE TITLE
Verschiedene Änderungen

### ISSUE THREAD

**Issue by hornschorsch** [607011/wordle-c#2]
Hallo,

vielen Dank für die Artikel über C-Programmierung und Github in der ct Nr. 25. Ich habe in den 90ern viel und gerne in C programmiert aber leider nie mit git(hub) gearbeitet, daher habe ich dieses Programm als Versuchskaninchen genommen um ein Repo zu forken, Änderungen zu machen und einen Pullrequest zu erstellen. Würde mich freuen wenn er angenommen wird.

Das Programm hat folgende Fehler oder Unschönheiten:

Die Liste in words.c kann man einfach als char *words[] deklarieren und dann mit NULL terminieren, so muss man nicht die Konstante NUM_WORDS verwalten. Am Programmanfang muss man dann die Worte einmal zählen.

Das Einlesen der geratenen  Worte und die Abfrage ob nochmal gespielt werden soll, funktionierte nicht richtig wenn der Benutzer zu wenig Zeichen eingibt oder bei der Abrage nicht nur Enter drückt sondern "J(a)" eingibt.

Die Erkennung der vorhandenen aber fehlplazierten Buchstaben funktionierte nicht, beim Wort "cebit" und der Eingabe "teste" wurden beide "t" und "e" gelb angezeigt, obwohl sie nur einmal im gesuchten Wort vorkommen. Man braucht ein weiteres Array um sich zu merken ob ein Buchstabe bereits benutzt wurde.

**Comment by 607011** [comment]
Vielen Dank für Ihre Mühen! Den Pull-Request schaue ich mir gerne an. Die Idee, Wörter zu zählen, finde ich gut. Zu dem neuen Array `used` äußere ich mich im [Pull-Request](https://github.com/607011/wordle-c/pull/1).
