### ISSUE TITLE
get_input endet nur, wenn Worte aus Liste eingegeben, ist das gewollt ?

### ISSUE THREAD

**Issue by Achim-Haag** [607011/wordle-c#3]
Habe den c't Artikel zum Anlass genommen, mich in C einzuarbeiten (MVSC aus Visualstudio 2022).

Allerdings zeigt sich bei mir das Verhalten, dass die do-while Schleife in get_input nur verlassen wird, wenn ich ein Wort aus der Wortliste eingebe, daher bekomme ich für Nicht-Wortlisten-Eingaben keine Buchstaben-Hinweise, sondern nur den printf "Das Wort ist nicht in der Liste erlaubter Wörter.".

Ich hatte die Source aus Lerngründen abgetippt und dachte zunächst an einen Eingabefehler, das Verhalten zeigt sich aber auch beim Einkopieren aus der Github-Source.

Schuld ist die do-while Schleife in get_input, genauer: word_is_allowed prüft, ob mein geratenes Wort in der Wortliste ist, wenn nicht, wird bad_word auf true gesetzt und damit ist die while-Bedingung erfüllt.

```
	} else {
	    bad_word = !word_is_allowed(state->guess);
	    if (bad_word)
		    printf("Das Wort ist nicht in der Liste erlaubter Wörter.\n");
	}
    }
    while (bad_word);
```

Gebe ich ein (anderes) Wort aus der Wortliste ein, wird die do-while Schleife verlassen und ich bekomme die Buchstaben-Hinweise

Meine Frage: ist das Verhalten so gewollt ?
Muss ich also ein Wort aus der Wortliste erwischen, um die Buchstaben-Hinweise zu bekommen ?
Oder ist das eine Macke des Microsoft C-Compilers, die sich mir nicht erschließt ?

**Comment by 607011** [comment]
Das ist gewollt, weil es verhindert, dass Spieler ausgedachte Buchstabenfolgen eintippen, um schneller auf das gesuchte Wort zu kommen. Für Ihre eigene Version des Spiels können Sie die Abfrage gerne rausnehmen ;-)

**Comment by Achim-Haag** [comment]
Danke für die Info, also kein Tippfehler meinerseits.
Die [Modifikation hab ich eingebaut](https://github.com/Achim-Haag/My_First_C_Program), mir geht es aber mehr um den Einstieg in C sowie den Umgang mit Github, wie es im c't Folgeartikel beschrieben war.
